### ISSUE TITLE
pyamf.DecodeError: Malformed stream (amfVersion=15423)

### ISSUE THREAD

**Issue by bastetcheat** [StdCarrot/Py3AMF#16]
C:\xampp_2015\htdocs\Py3AMF>a
Traceback (most recent call last):
  File "C:\xampp_2015\htdocs\Py3AMF\test.py", line 24, in <module>
    resp_msg = remoting.decode(resp.content)
  File "C:\xampp_2015\htdocs\Py3AMF\pyamf\remoting\__init__.py", line 631, in decode
    raise pyamf.DecodeError(
pyamf.DecodeError: Malformed stream (amfVersion=15423)

**Comment by StdCarrot** [comment]
Couldn't track a problem without data.
Check your data first and upload it to a issue.
